# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LegendDataSlider
                                 A QGIS plugin
 Filter layer elements from the legend, using sliders that cover a value of each numeric field.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-24
        copyright            : (C) 2024 by W.C.N. Vessies
        email                : wcn.vessies@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LegendDataSlider class from file LegendDataSlider.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .legend_data_slider import LegendDataSlider
    return LegendDataSlider(iface)
